import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the initial state for the slice
interface UndefinedFieldState {
  fields: string[];
}

const initialState: UndefinedFieldState = {
  fields: [],
};

// Create the Redux slice
const undefinedFieldSlice = createSlice({
  name: "undefinedFields",
  initialState,
  reducers: {
    // Reducer to set fields with a payload of string array
    setFields(state, action: PayloadAction<string[]>) {
      state.fields = action.payload; // Set the payload as the new fields
    },
    // Reducer to clear fields (reset to empty array)
    clearFields(state) {
      state.fields = [];
    },
  },
});

// Export the actions generated by createSlice
export const undefinedFieldActions = undefinedFieldSlice.actions;

// Export the reducer to be used in the store configuration
export default undefinedFieldSlice;
