export const POST_DETAILS_PRIORITY: { [key: string]: string[] } = {
  latest_job: [
    "latest_job_ref.name_of_the_post",
    "common_ref.short_information",
    "common_ref.department",
    "common_ref.stage_level",
    "common_ref.eligibility",
    "common_ref.applicants",
    "latest_job_ref.how_to_fill_the_form",
    "common_ref.age_criteria",
    "common_ref.vacancy",
    "date_ref",
    "link_ref",
    "fee_ref",
  ],
  result: [
    "result_ref.name_of_the_post",
    "common_ref.short_information",
    "common_ref.department",
    "common_ref.stage_level",
    "common_ref.applicants",
    "result_ref.how_to_download_result",
    "result_ref.result",
    "link_ref",
    "common_ref.vacancy",
  ],
  admit_card: [
    "admit_card_ref.name_of_the_post",
    "common_ref.short_information",
    "common_ref.department",
    "common_ref.stage_level",
    "common_ref.applicants",
    "admit_card_ref.how_to_download_admit_card",
    "date_ref",
    "common_ref.post_exam_mode",
    "common_ref.applicants_gender_that_can_apply",
    "common_ref.post_importance",
    "syllabus_ref.syllabus",
    "link_ref",
    "common_ref.job_type",
    "common_ref.post_exam_duration",
    "common_ref.post_exam_toughness_ranking",
    "common_ref.vacancy.detail"
  ],
  answer_key: [
    "answer_key_ref.name_of_the_post",
    "common_ref.short_information",
    "common_ref.department",
    "common_ref.stage_level",
    "common_ref.applicants",
    "answer_key_ref.how_to_download_answer_key",
    "date_ref",
    "link_ref",
    "common_ref.vacancy",
  ],
  admission: [
    "admission_ref.name_of_the_post",
    "common_ref.short_information",
    "common_ref.department",
    "common_ref.stage_level",
    "common_ref.applicants",
    "date_ref",
    "link_ref",
  ],
  certificate_verification: [
    "certificate_verification_ref.name_of_the_post",
    "common_ref.short_information",
    "common_ref.department",
    "date_ref",
    "link_ref",
  ],
  important: [
    "important_ref.name_of_the_post",
    "common_ref.short_information",
    "common_ref.department",
    "common_ref.stage_level",
    "common_ref.applicants",
    "date_ref",
    "link_ref",
  ],
  syllabus: [
    "syllabus_ref.name_of_the_post",
    "common_ref.short_information",
    "common_ref.department",
    "common_ref.stage_level",
    "syllabus_ref.syllabus",
    "date_ref",
    "link_ref",
  ],
};

export const excludedKeys = [
  "_id",
  "created_by",
  "createdAt",
  "updatedAt",
  "contributors",
  "is_saved",
  "__v",
  "post_code",
  "version",
  "admit_card_ref",
  "certificate_verification_ref",
  "result_ref",
  "answer_key_ref",
  "latest_job_ref",
  "latest_job_ref",
];

export const notDisplayKeys = [];

export const tableRequired = [
  "age_criteria",
  "result_ref.result",
  "male",
  "female",
  "other",
  "common_ref.vacancy.category_wise",
  "link_ref",
  "date_ref",
  "eligibility",
  "applicants",
  "fee_ref.category_wise",
  "common_ref.age_criteria",
  "link_ref.additional_resources",
  "result_ref.result.current_year",
  "result_ref.result.previous_year",
];

export const excludedPostListKeys = [
  "_id",
  "name_of_the_post",
  "updatedAt",
  "is_saved",
  "approved",
  "contributors",
  "__v",
  "post_code",
  "admit_card_ref",
  "result_ref",
  "certificate_verification_ref",
  "admission_ref",
  "latest_job_ref",
  "answer_key_ref",
  "syllabus_ref",
  "admission_ref",
  "important_ref",
  "version",
];
